title       = "hn"
baseURL     = "https://hackernews-cli.tamnd.com/"
description = "A command line for Hacker News."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/hackernews-cli"
